version: '3'

services: 
  bocadilloweb:
    build: 
      context: .
      dockerfile: bocadillo.Dockerfile
    expose: 
      - "80"
    image: bocadillo-custom
    networks: 
      - proxy
    volumes: 
    - ./app:/app

  staticproxy:
    build: 
      context: .
      dockerfile: nginxstaticproxy.Dockerfile
    depends_on: 
      - bocadilloweb
    networks: 
      - proxy
    ports:
      - "80:80"
    volumes: 
      - ./app/static:/static
    
networks: 
  proxy:
    driver: bridge
